package com.example.roomxxx0102.logic.pointing

data class DevicePointingScoringConfig(
    val hotspotRadiusScale: Float = 0.18f,
    val hotspotRadiusMinPx: Float = 20f,
    val hotspotRadiusMaxPx: Float = 60f,
    val polygonAssistRadiusScale: Float = 0.35f,
    val polygonAssistRadiusMinPx: Float = 30f,
    val polygonAssistRadiusMaxPx: Float = 100f,
    val nearFieldExemptDistanceScale: Float = 0.50f,
    val backwardToleranceScale: Float = 1.00f,
    val penetrationNormLengthScale: Float = 0.50f,
    val baseNearFieldCropScale: Float = 0.60f,
    val baseNearFieldCropMinPx: Float = 40f,
    val baseNearFieldCropMaxPx: Float = 120f,
    val absoluteNearExemptScale: Float = 0.08f,
    val absoluteNearExemptMinPx: Float = 15f,
    val absoluteNearExemptMaxPx: Float = 35f,
    val nearFieldDeviceDistanceMinPx: Float = 100f,
    val nearFieldDeviceDistanceScale: Float = 1.50f,
    val minimumUsableConfidence: Float = 0.25f,
    val polygonDirectionCosFloor: Float = 0.50f,
    val nearFieldDirectionCosFloor: Float = 0.26f,
    val hotspotWeightBase: Float = 0.70f,
    val hotspotWeightBoostByNearFieldSupport: Float = 0.10f,
    val polygonDirectionPower: Float = 1.50f,
    val frameHitGeometricThreshold: Float = 0.65f,
    val frameLeadRatioThreshold: Float = 1.15f,
    val timeoutMs: Long = 500L,
    val finalAverageWeight: Float = 0.70f,
    val finalPeakWeight: Float = 0.15f,
    val finalLeadWeight: Float = 0.15f,
    val baselineFinalThreshold: Float = 0.45f,
    val absoluteMinimumFinalThreshold: Float = 0.20f,
    val minimumWeightedHitRatio: Float = 0.20f,
    val minimumFinalLeadRatio: Float = 1.20f,
    val forceOutputOnLowConfidence: Boolean = false
)
